update

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -59,13 +59,13 @@ then
 fi
 
 # Check if there are any uncommitted changes
-if ! git diff-index --quiet HEAD --; then
-    echo "Changes to the following files are uncommitted:"
-    git diff-index --name-only HEAD --
-    echo "Please commit the changes before proceeding."
-    echo "Aborting."
-    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
-fi
+# if ! git diff-index --quiet HEAD --; then
+#     echo "Changes to the following files are uncommitted:"
+#     git diff-index --name-only HEAD --
+#     echo "Please commit the changes before proceeding."
+#     echo "Aborting."
+#     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+# fi
 
 # Check if there are any untracked files
 if ! test -z "$(git ls-files --exclude-standard --others)"; then
@@ -92,6 +92,7 @@ fi
 git checkout -b $DEPLOY_BRANCH
 
 # Build site
+bundle update uri
 bundle exec jekyll build
 
 # Delete and move files
